package agents

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ImplementationStatusIntentOnly is the only allowed implementation status for Coder.
const ImplementationStatusIntentOnly = "intent_only"

// DangerousStatuses are implementation statuses that must be rejected.
var DangerousStatuses = []string{
	"implemented",
	"applied",
	"done",
	"patched",
	"executed",
	"modified",
	"committed",
	"pushed",
}

// DangerousContentPatterns are patterns that indicate real patch/diff content.
var DangerousContentPatterns = []string{
	"diff --git",
	"unified diff",
	"git apply",
	"patch applied",
	"files modified",
	"committed",
	"pushed",
	"test executed",
	"shell execution",
	"command executed",
}

// CoderPatchIntent represents a patch intent generated by the Coder.
// It does NOT contain real diffs, only intent descriptions.
type CoderPatchIntent struct {
	Goal                  string              `json:"goal"`
	PlanSummary           string              `json:"plan_summary"`
	ImplementationStatus  string              `json:"implementation_status"`
	FilesToChange         []PatchIntentFile   `json:"files_to_change"`
	Changes               []PatchIntentChange `json:"changes"`
	Risks                 []string            `json:"risks"`
	ValidationSuggestions []string            `json:"validation_suggestions"`
	NoFileWrites          bool                `json:"no_file_writes"`
}

// PatchIntentFile represents a file to be changed.
type PatchIntentFile struct {
	Path       string `json:"path"`
	ChangeType string `json:"change_type"`
	Reason     string `json:"reason"`
	RiskLevel  string `json:"risk_level"`
}

// PatchIntentChange represents a specific change to be made.
type PatchIntentChange struct {
	ID             string `json:"id"`
	FilePath       string `json:"file_path"`
	Description    string `json:"description"`
	ExpectedEffect string `json:"expected_effect"`
	SafetyNotes    string `json:"safety_notes"`
}

// Validate checks that the intent has all required fields and is safe.
func (ci *CoderPatchIntent) Validate() error {
	if ci.Goal == "" {
		return fmt.Errorf("coder: goal is required")
	}
	if ci.PlanSummary == "" {
		return fmt.Errorf("coder: plan_summary is required")
	}
	if len(ci.FilesToChange) == 0 {
		return fmt.Errorf("coder: files_to_change is required")
	}
	if len(ci.Changes) == 0 {
		return fmt.Errorf("coder: changes is required")
	}
	if ci.ImplementationStatus != ImplementationStatusIntentOnly {
		return fmt.Errorf("coder: implementation_status must be %q, got %q", ImplementationStatusIntentOnly, ci.ImplementationStatus)
	}
	if !ci.NoFileWrites {
		return fmt.Errorf("coder: no_file_writes must be true")
	}
	return nil
}

// ParseCoderIntentResponse parses an LLM response into a CoderPatchIntent.
// Supports:
//   - Pure JSON
//   - Markdown code block wrapped JSON
//   - Returns clear parse error for invalid JSON
//   - Returns clear parse error for missing required fields
func ParseCoderIntentResponse(text string) (*CoderPatchIntent, error) {
	// Try to extract JSON from markdown code blocks
	jsonStr := extractJSON(text)

	// Parse JSON
	var intent CoderPatchIntent
	if err := json.Unmarshal([]byte(jsonStr), &intent); err != nil {
		return nil, fmt.Errorf("coder: invalid JSON: %w", err)
	}

	// Force safe values
	intent.ImplementationStatus = ImplementationStatusIntentOnly
	intent.NoFileWrites = true

	// Validate
	if err := intent.Validate(); err != nil {
		return nil, err
	}

	return &intent, nil
}

// ValidateCoderIntent validates that a CoderPatchIntent is safe.
// Returns an error if the intent contains dangerous patterns.
func ValidateCoderIntent(intent *CoderPatchIntent) error {
	// Check implementation_status
	for _, dangerous := range DangerousStatuses {
		if strings.EqualFold(intent.ImplementationStatus, dangerous) {
			return fmt.Errorf("coder: dangerous implementation_status %q detected, must be %q", intent.ImplementationStatus, ImplementationStatusIntentOnly)
		}
	}

	// Check no_file_writes
	if !intent.NoFileWrites {
		return fmt.Errorf("coder: no_file_writes must be true")
	}

	// Check for dangerous content in changes
	for _, change := range intent.Changes {
		if err := validateChangeContent(change); err != nil {
			return err
		}
	}

	// Check for dangerous content in files_to_change
	for _, file := range intent.FilesToChange {
		if err := validateFileContent(file); err != nil {
			return err
		}
	}

	return nil
}

// validateChangeContent checks that a change doesn't contain dangerous patterns.
func validateChangeContent(change PatchIntentChange) error {
	content := strings.ToLower(change.Description + " " + change.ExpectedEffect + " " + change.SafetyNotes)
	for _, pattern := range DangerousContentPatterns {
		if strings.Contains(content, strings.ToLower(pattern)) {
			return fmt.Errorf("coder: dangerous content pattern %q detected in change %q", pattern, change.ID)
		}
	}
	return nil
}

// validateFileContent checks that a file intent doesn't contain dangerous patterns.
func validateFileContent(file PatchIntentFile) error {
	content := strings.ToLower(file.Path + " " + file.ChangeType + " " + file.Reason + " " + file.RiskLevel)
	for _, pattern := range DangerousContentPatterns {
		if strings.Contains(content, strings.ToLower(pattern)) {
			return fmt.Errorf("coder: dangerous content pattern %q detected in file %q", pattern, file.Path)
		}
	}
	return nil
}

// FormatCoderIntent formats a CoderPatchIntent for display.
func FormatCoderIntent(intent *CoderPatchIntent) string {
	var buf strings.Builder

	fmt.Fprintf(&buf, "Coder Patch Intent:\n")
	fmt.Fprintf(&buf, "  Goal: %s\n", intent.Goal)
	fmt.Fprintf(&buf, "  Plan Summary: %s\n", intent.PlanSummary)
	fmt.Fprintf(&buf, "  Status: %s\n", intent.ImplementationStatus)
	fmt.Fprintf(&buf, "\n")

	fmt.Fprintf(&buf, "Files:\n")
	for _, file := range intent.FilesToChange {
		fmt.Fprintf(&buf, "  - %s\n", file.Path)
		fmt.Fprintf(&buf, "    change_type: %s\n", file.ChangeType)
		fmt.Fprintf(&buf, "    reason: %s\n", file.Reason)
		fmt.Fprintf(&buf, "    risk_level: %s\n", file.RiskLevel)
	}

	fmt.Fprintf(&buf, "\nChanges:\n")
	for i, change := range intent.Changes {
		fmt.Fprintf(&buf, "  %d. %s\n", i+1, change.Description)
		fmt.Fprintf(&buf, "     File: %s\n", change.FilePath)
		fmt.Fprintf(&buf, "     Effect: %s\n", change.ExpectedEffect)
		if change.SafetyNotes != "" {
			fmt.Fprintf(&buf, "     Safety: %s\n", change.SafetyNotes)
		}
	}

	if len(intent.Risks) > 0 {
		fmt.Fprintf(&buf, "\nRisks:\n")
		for _, risk := range intent.Risks {
			fmt.Fprintf(&buf, "  - %s\n", risk)
		}
	}

	if len(intent.ValidationSuggestions) > 0 {
		fmt.Fprintf(&buf, "\nValidation Suggestions:\n")
		for _, suggestion := range intent.ValidationSuggestions {
			fmt.Fprintf(&buf, "  - %s\n", suggestion)
		}
	}

	fmt.Fprintf(&buf, "\nNo files were modified.\n")
	fmt.Fprintf(&buf, "No patch was generated.\n")
	fmt.Fprintf(&buf, "No tools were executed.\n")

	return buf.String()
}

// FormatCoderIntentJSON formats a CoderPatchIntent as JSON.
func FormatCoderIntentJSON(intent *CoderPatchIntent) (string, error) {
	data, err := json.MarshalIndent(intent, "", "  ")
	if err != nil {
		return "", fmt.Errorf("coder: marshal JSON: %w", err)
	}
	return string(data), nil
}
