package agents

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ImplementationStatusPlanOnly is the only allowed implementation status.
const ImplementationStatusPlanOnly = "plan_only"

// AgentPlan represents a structured plan generated by the Planner LLM.
type AgentPlan struct {
	Goal                  string     `json:"goal"`
	Summary               string     `json:"summary"`
	Steps                 []PlanStep `json:"steps"`
	Risks                 []string   `json:"risks"`
	FilesMaybeAffected    []string   `json:"files_maybe_affected"`
	ValidationSuggestions []string   `json:"validation_suggestions"`
	ImplementationStatus  string     `json:"implementation_status"`
	PrefixFingerprint     string     `json:"prefix_fingerprint,omitempty"`
	ContextBytes          int        `json:"context_bytes,omitempty"`
}

// PlanStep represents a single step in an AgentPlan.
type PlanStep struct {
	ID             string   `json:"id"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	RiskLevel      string   `json:"risk_level"`
	ExpectedFiles  []string `json:"expected_files"`
	ValidationHint string   `json:"validation_hint"`
}

// Validate checks that the plan has all required fields and ImplementationStatus is plan_only.
func (p *AgentPlan) Validate() error {
	if p.Goal == "" {
		return fmt.Errorf("plan: goal is required")
	}
	if p.Summary == "" {
		return fmt.Errorf("plan: summary is required")
	}
	if len(p.Steps) == 0 {
		return fmt.Errorf("plan: steps is required")
	}
	if p.ImplementationStatus != ImplementationStatusPlanOnly {
		return fmt.Errorf("plan: implementation_status must be %q, got %q", ImplementationStatusPlanOnly, p.ImplementationStatus)
	}
	return nil
}

// ParsePlanResponse parses an LLM response into an AgentPlan.
// Supports:
//   - Pure JSON
//   - Markdown code block wrapped JSON
//   - Returns clear parse error for invalid JSON
//   - Returns clear parse error for missing required fields
func ParsePlanResponse(text string) (*AgentPlan, error) {
	// Try to extract JSON from markdown code blocks
	jsonStr := extractJSON(text)

	// Parse JSON
	var plan AgentPlan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err != nil {
		return nil, fmt.Errorf("plan: invalid JSON: %w", err)
	}

	// Force ImplementationStatus to plan_only
	plan.ImplementationStatus = ImplementationStatusPlanOnly

	// Validate
	if err := plan.Validate(); err != nil {
		return nil, err
	}

	return &plan, nil
}

// extractJSON extracts JSON from text, handling markdown code blocks.
func extractJSON(text string) string {
	text = strings.TrimSpace(text)

	// Try to find JSON in markdown code blocks
	if idx := strings.Index(text, "```json"); idx >= 0 {
		start := idx + len("```json")
		end := strings.Index(text[start:], "```")
		if end >= 0 {
			return strings.TrimSpace(text[start : start+end])
		}
	}

	// Try to find JSON in code blocks without language specifier
	if idx := strings.Index(text, "```"); idx >= 0 {
		start := idx + len("```")
		end := strings.Index(text[start:], "```")
		if end >= 0 {
			return strings.TrimSpace(text[start : start+end])
		}
	}

	// Try to find raw JSON object
	if idx := strings.Index(text, "{"); idx >= 0 {
		end := strings.LastIndex(text, "}")
		if end > idx {
			return text[idx : end+1]
		}
	}

	return text
}

// FormatPlan formats an AgentPlan for display.
func FormatPlan(plan *AgentPlan) string {
	var buf strings.Builder

	fmt.Fprintf(&buf, "Plan:\n")
	fmt.Fprintf(&buf, "  Goal: %s\n", plan.Goal)
	fmt.Fprintf(&buf, "  Summary: %s\n", plan.Summary)
	fmt.Fprintf(&buf, "  Status: %s\n", plan.ImplementationStatus)
	fmt.Fprintf(&buf, "\n")

	fmt.Fprintf(&buf, "Steps:\n")
	for i, step := range plan.Steps {
		fmt.Fprintf(&buf, "  %d. [%s] %s\n", i+1, step.RiskLevel, step.Title)
		fmt.Fprintf(&buf, "     %s\n", step.Description)
		if len(step.ExpectedFiles) > 0 {
			fmt.Fprintf(&buf, "     Files: %s\n", strings.Join(step.ExpectedFiles, ", "))
		}
		if step.ValidationHint != "" {
			fmt.Fprintf(&buf, "     Validation: %s\n", step.ValidationHint)
		}
	}

	if len(plan.Risks) > 0 {
		fmt.Fprintf(&buf, "\nRisks:\n")
		for _, risk := range plan.Risks {
			fmt.Fprintf(&buf, "  - %s\n", risk)
		}
	}

	if len(plan.FilesMaybeAffected) > 0 {
		fmt.Fprintf(&buf, "\nFiles Maybe Affected:\n")
		for _, file := range plan.FilesMaybeAffected {
			fmt.Fprintf(&buf, "  - %s\n", file)
		}
	}

	if len(plan.ValidationSuggestions) > 0 {
		fmt.Fprintf(&buf, "\nValidation Suggestions:\n")
		for _, suggestion := range plan.ValidationSuggestions {
			fmt.Fprintf(&buf, "  - %s\n", suggestion)
		}
	}

	if plan.PrefixFingerprint != "" {
		fmt.Fprintf(&buf, "\nPrefix Fingerprint: %s\n", plan.PrefixFingerprint)
		fmt.Fprintf(&buf, "Context Bytes: %d\n", plan.ContextBytes)
	}

	fmt.Fprintf(&buf, "\nNo files were modified.\n")
	fmt.Fprintf(&buf, "No tools were executed.\n")
	fmt.Fprintf(&buf, "No patch was generated.\n")

	return buf.String()
}

// FormatPlanJSON formats an AgentPlan as JSON.
func FormatPlanJSON(plan *AgentPlan) (string, error) {
	data, err := json.MarshalIndent(plan, "", "  ")
	if err != nil {
		return "", fmt.Errorf("plan: marshal JSON: %w", err)
	}
	return string(data), nil
}
